<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE object
[
   <!ELEMENT object (#PCDATA | object)*>
   <!ATTLIST object name      CDATA #REQUIRED>
   <!ATTLIST object class     CDATA #REQUIRED>
   <!ATTLIST object primitive CDATA "no">
   <!ATTLIST object array     CDATA "no">   <!-- the dimensions of the array; no=0, yes=1 -->
   <!ATTLIST object null      CDATA "no">
   <!ATTLIST object version   CDATA "3.5.3">
]
>

<object class="java.util.Vector" name="__root__" version="3.5.3">
   <object class="weka.classifiers.trees.J48" name="0">
      <object array="yes" class="java.lang.String" name="options">
         <object class="java.lang.String" name="0">-S</object>
         <object class="java.lang.String" name="1">-C</object>
         <object class="java.lang.String" name="2">0.25</object>
         <object class="java.lang.String" name="3">-B</object>
         <object class="java.lang.String" name="4">-M</object>
         <object class="java.lang.String" name="5">2</object>
         <object class="java.lang.String" name="6"/>
         <object class="java.lang.String" name="7"/>
         <object class="java.lang.String" name="8"/>
         <object class="java.lang.String" name="9"/>
         <object class="java.lang.String" name="10"/>
         <object class="java.lang.String" name="11"/>
         <object class="java.lang.String" name="12"/>
         <object class="java.lang.String" name="13"/>
      </object>
   </object>
   <object class="weka.classifiers.trees.J48" name="1">
      <object array="yes" class="java.lang.String" name="options">
         <object class="java.lang.String" name="0">-S</object>
         <object class="java.lang.String" name="1">-C</object>
         <object class="java.lang.String" name="2">0.25</object>
         <object class="java.lang.String" name="3">-B</object>
         <object class="java.lang.String" name="4">-M</object>
         <object class="java.lang.String" name="5">2</object>
         <object class="java.lang.String" name="6">-A</object>
         <object class="java.lang.String" name="7"/>
         <object class="java.lang.String" name="8"/>
         <object class="java.lang.String" name="9"/>
         <object class="java.lang.String" name="10"/>
         <object class="java.lang.String" name="11"/>
         <object class="java.lang.String" name="12"/>
         <object class="java.lang.String" name="13"/>
      </object>
   </object>
   <object class="weka.classifiers.trees.J48" name="2">
      <object array="yes" class="java.lang.String" name="options">
         <object class="java.lang.String" name="0">-S</object>
         <object class="java.lang.String" name="1">-C</object>
         <object class="java.lang.String" name="2">0.25</object>
         <object class="java.lang.String" name="3">-M</object>
         <object class="java.lang.String" name="4">2</object>
         <object class="java.lang.String" name="5"/>
         <object class="java.lang.String" name="6"/>
         <object class="java.lang.String" name="7"/>
         <object class="java.lang.String" name="8"/>
         <object class="java.lang.String" name="9"/>
         <object class="java.lang.String" name="10"/>
         <object class="java.lang.String" name="11"/>
         <object class="java.lang.String" name="12"/>
         <object class="java.lang.String" name="13"/>
      </object>
   </object>
   <object class="weka.classifiers.trees.J48" name="3">
      <object array="yes" class="java.lang.String" name="options">
         <object class="java.lang.String" name="0">-S</object>
         <object class="java.lang.String" name="1">-C</object>
         <object class="java.lang.String" name="2">0.25</object>
         <object class="java.lang.String" name="3">-M</object>
         <object class="java.lang.String" name="4">2</object>
         <object class="java.lang.String" name="5">-A</object>
         <object class="java.lang.String" name="6"/>
         <object class="java.lang.String" name="7"/>
         <object class="java.lang.String" name="8"/>
         <object class="java.lang.String" name="9"/>
         <object class="java.lang.String" name="10"/>
         <object class="java.lang.String" name="11"/>
         <object class="java.lang.String" name="12"/>
         <object class="java.lang.String" name="13"/>
      </object>
   </object>
   <object class="weka.classifiers.trees.J48" name="4">
      <object array="yes" class="java.lang.String" name="options">
         <object class="java.lang.String" name="0">-S</object>
         <object class="java.lang.String" name="1">-C</object>
         <object class="java.lang.String" name="2">0.5</object>
         <object class="java.lang.String" name="3">-B</object>
         <object class="java.lang.String" name="4">-M</object>
         <object class="java.lang.String" name="5">2</object>
         <object class="java.lang.String" name="6"/>
         <object class="java.lang.String" name="7"/>
         <object class="java.lang.String" name="8"/>
         <object class="java.lang.String" name="9"/>
         <object class="java.lang.String" name="10"/>
         <object class="java.lang.String" name="11"/>
         <object class="java.lang.String" name="12"/>
         <object class="java.lang.String" name="13"/>
      </object>
   </object>
   <object class="weka.classifiers.trees.J48" name="5">
      <object array="yes" class="java.lang.String" name="options">
         <object class="java.lang.String" name="0">-S</object>
         <object class="java.lang.String" name="1">-C</object>
         <object class="java.lang.String" name="2">0.5</object>
         <object class="java.lang.String" name="3">-B</object>
         <object class="java.lang.String" name="4">-M</object>
         <object class="java.lang.String" name="5">2</object>
         <object class="java.lang.String" name="6">-A</object>
         <object class="java.lang.String" name="7"/>
         <object class="java.lang.String" name="8"/>
         <object class="java.lang.String" name="9"/>
         <object class="java.lang.String" name="10"/>
         <object class="java.lang.String" name="11"/>
         <object class="java.lang.String" name="12"/>
         <object class="java.lang.String" name="13"/>
      </object>
   </object>
   <object class="weka.classifiers.trees.J48" name="6">
      <object array="yes" class="java.lang.String" name="options">
         <object class="java.lang.String" name="0">-S</object>
         <object class="java.lang.String" name="1">-C</object>
         <object class="java.lang.String" name="2">0.5</object>
         <object class="java.lang.String" name="3">-M</object>
         <object class="java.lang.String" name="4">2</object>
         <object class="java.lang.String" name="5"/>
         <object class="java.lang.String" name="6"/>
         <object class="java.lang.String" name="7"/>
         <object class="java.lang.String" name="8"/>
         <object class="java.lang.String" name="9"/>
         <object class="java.lang.String" name="10"/>
         <object class="java.lang.String" name="11"/>
         <object class="java.lang.String" name="12"/>
         <object class="java.lang.String" name="13"/>
      </object>
   </object>
   <object class="weka.classifiers.trees.J48" name="7">
      <object array="yes" class="java.lang.String" name="options">
         <object class="java.lang.String" name="0">-S</object>
         <object class="java.lang.String" name="1">-C</object>
         <object class="java.lang.String" name="2">0.5</object>
         <object class="java.lang.String" name="3">-M</object>
         <object class="java.lang.String" name="4">2</object>
         <object class="java.lang.String" name="5">-A</object>
         <object class="java.lang.String" name="6"/>
         <object class="java.lang.String" name="7"/>
         <object class="java.lang.String" name="8"/>
         <object class="java.lang.String" name="9"/>
         <object class="java.lang.String" name="10"/>
         <object class="java.lang.String" name="11"/>
         <object class="java.lang.String" name="12"/>
         <object class="java.lang.String" name="13"/>
      </object>
   </object>
   <object class="weka.classifiers.trees.J48" name="8">
      <object array="yes" class="java.lang.String" name="options">
         <object class="java.lang.String" name="0">-U</object>
         <object class="java.lang.String" name="1">-B</object>
         <object class="java.lang.String" name="2">-M</object>
         <object class="java.lang.String" name="3">2</object>
         <object class="java.lang.String" name="4"/>
         <object class="java.lang.String" name="5"/>
         <object class="java.lang.String" name="6"/>
         <object class="java.lang.String" name="7"/>
         <object class="java.lang.String" name="8"/>
         <object class="java.lang.String" name="9"/>
         <object class="java.lang.String" name="10"/>
         <object class="java.lang.String" name="11"/>
         <object class="java.lang.String" name="12"/>
         <object class="java.lang.String" name="13"/>
      </object>
   </object>
   <object class="weka.classifiers.trees.J48" name="9">
      <object array="yes" class="java.lang.String" name="options">
         <object class="java.lang.String" name="0">-U</object>
         <object class="java.lang.String" name="1">-B</object>
         <object class="java.lang.String" name="2">-M</object>
         <object class="java.lang.String" name="3">2</object>
         <object class="java.lang.String" name="4">-A</object>
         <object class="java.lang.String" name="5"/>
         <object class="java.lang.String" name="6"/>
         <object class="java.lang.String" name="7"/>
         <object class="java.lang.String" name="8"/>
         <object class="java.lang.String" name="9"/>
         <object class="java.lang.String" name="10"/>
         <object class="java.lang.String" name="11"/>
         <object class="java.lang.String" name="12"/>
         <object class="java.lang.String" name="13"/>
      </object>
   </object>
   <object class="weka.classifiers.trees.J48" name="10">
      <object array="yes" class="java.lang.String" name="options">
         <object class="java.lang.String" name="0">-U</object>
         <object class="java.lang.String" name="1">-M</object>
         <object class="java.lang.String" name="2">2</object>
         <object class="java.lang.String" name="3"/>
         <object class="java.lang.String" name="4"/>
         <object class="java.lang.String" name="5"/>
         <object class="java.lang.String" name="6"/>
         <object class="java.lang.String" name="7"/>
         <object class="java.lang.String" name="8"/>
         <object class="java.lang.String" name="9"/>
         <object class="java.lang.String" name="10"/>
         <object class="java.lang.String" name="11"/>
         <object class="java.lang.String" name="12"/>
         <object class="java.lang.String" name="13"/>
      </object>
   </object>
   <object class="weka.classifiers.trees.J48" name="11">
      <object array="yes" class="java.lang.String" name="options">
         <object class="java.lang.String" name="0">-U</object>
         <object class="java.lang.String" name="1">-M</object>
         <object class="java.lang.String" name="2">2</object>
         <object class="java.lang.String" name="3">-A</object>
         <object class="java.lang.String" name="4"/>
         <object class="java.lang.String" name="5"/>
         <object class="java.lang.String" name="6"/>
         <object class="java.lang.String" name="7"/>
         <object class="java.lang.String" name="8"/>
         <object class="java.lang.String" name="9"/>
         <object class="java.lang.String" name="10"/>
         <object class="java.lang.String" name="11"/>
         <object class="java.lang.String" name="12"/>
         <object class="java.lang.String" name="13"/>
      </object>
   </object>
</object>
